### ISSUE TITLE
`key_G` semantic of "missing" count broken

### ISSUE THREAD

**Issue by mkoskar** [GermainZ/weechat-vimode#12]
Typing `G` in buffer will not scroll to the end of buffer as intended but instead to the second line of buffer. Result is the same for `0G`. Reason being function `get_keys_and_count(combo)` will return `1` for all above cases, which doesn't seem to be expected by `key_G` implementation.

As a quick "fix" I've "disabled" count on `key_G`, I don't use it, and not sure if it makes sense (unless one can turn line numbering on, which is probably possible).

Secondary, to get closer to VIM e.g., `10G` should scroll such that the first line visible is the line 10 and not 11 as it seems to be now.

**Comment by GermainZ** [comment]
Thanks for reporting this. Both issues should be fixed in e6af4ee5eec0ebd8338b3b9d3051a88d9e59bbb5 and fcb0a15b88eaf950e4dd29c65cb53551cb9fa810.

> (unless one can turn line numbering on, which is probably possible).

Line numbering could be used for useful things, like yanking lines from the buffer by their number (e.g. `:20,24y` or `:28y`). This should be done with dynamic line numbering (that is, the lines currently *displayed* in your buffer should start at 0), though. It will be trickier to implement (or it might not be possible at all in an efficient manner) -- I'll have to look into it.
