### ISSUE TITLE
Yank doesn't seem to work on Ubuntu 14.04 via SSH via Mac OS X 10.12.3 via iTerm w/ Weechat 1.7.  xclip is installed.  

### ISSUE THREAD

**Issue by arooni** [GermainZ/weechat-vimode#45]
To be clear, I'm SSH'ing FROM Mac OS X to Ubuntu 14.04.  So xclip is installed as covered in an earlier issue.  

I see: "Can't open display:8(null)"

By the way, when I'm on my Ubuntu 16.04 laptop, yank works fine.  But when I try to SSH from that laptop to my Ubuntu server, the same error occurs.  Seems to have something to do with the SSH session.  

when I to try yy (yank) some text.  

Ideas?

Thanks!

**Comment by GermainZ** [comment]
You'll need X11 forwarding. [This](https://askubuntu.com/questions/305654/xclip-on-headless-server/305681#305681) is a pretty good answer about it.

**Comment by arooni** [comment]
Well on Ubuntu I do have X11 forwarding turned on... and yet yank doesn't seem to work within weechat.  Again, no problem connected locally.

**Comment by GermainZ** [comment]
I'm afraid I can't really help you since I'm not familiar with how the
setup would be between Ubuntu and macOS, but this isn't an issue with
weechat-vimode. I'd be happy to add a solution to the FAQ if you find one,
so please let me know.


On Mar 5, 2017 4:53 AM, "arooni" <notifications@github.com> wrote:

Well on Ubuntu I do have X11 forwarding turned on... and yet yank doesn't
seem to work within weechat. Again, no problem connected locally.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/GermainZ/weechat-vimode/issues/45#issuecomment-284201168>,
or mute the thread

**Comment by arooni** [comment]
I'm sorry for my lack of clarification.  I have both a Ubuntu laptop and a Mac desktop.  Connecting from the ubuntu laptop (16.04) to my ubuntu server (14.04) still shows same issue.  X11 forwarding is setup correctly.   

Maybe this isn't really the use case you're enabling for though as connecting to ssh to then use weechat is a bit strange lol... but I do love having access to weechat across all my tmux sessions
