### ISSUE TITLE
vi_cmd doesn't stay visible.

### ISSUE THREAD

**Issue by aranmohyeddin** [GermainZ/weechat-vimode#55]
I do `:set weechat.bar.vi_cmd.hidden on` and then the vi_cmd becomes visible in insert mode but as soon as I press ESC again and go to normal mode it disappears. my condition value is "" if that matters.

**Comment by aranmohyeddin** [comment]
My friend sim642 in IRC helped figured out that the issue is with this [line](https://github.com/GermainZ/weechat-vimode/blob/master/vimode.py#L918) I removed that line and now the problem is solved for me. but of course that line shouldn't be removed but rather put in an if condition for people who don't want to keep the bar visible all the time.

**Comment by aranmohyeddin** [comment]
also line 1057 has this problem. If I backspace until the cmd line becomes empty it will be hidden. also there is an occurrence in line 1163 which makes problems with the search mode and if that is also removed and also there is a line for showing that I also have removed. after all this all the problems are fixed there is only this small issue that when searching the search text is written both in vi_cmd bar and input bar.

**Comment by GermainZ** [comment]
Just wanted to make sure I understood your use case.

An option to permanently show vi_cmd can be added. I think I'll do something like the following:

- Add a bar item that contains the same text as vi_cmd. You can place this anywhere if you want 
- Add an option that controls the behavior of vi_cmd: always visible, always hidden or the default behavior (which is how it currently behaves).

You can then customize your setup to suit you 

>search queries appearing twice which I don't care so much about.

Unfortunately, there isn't much I can do about that.

**Comment by aranmohyeddin** [comment]
What do you think about just eliminative the vi_cmd? I don't really see any use in it? why does it need to be a separate bar why can't we just use the already available inputbar?

**Comment by aranmohyeddin** [comment]
I don't understand why you want to add a new bar item? why don't you just but 3-4 if statements in the code to check if that option is set to default and only show/hide the vi_cmd if it is set to default?

**Comment by GermainZ** [comment]
>What do you think about just eliminative the vi_cmd? I don't really see any use in it? why does it need to be a separate bar why can't we just use the already available inputbar?

I think it makes more sense:

- It's a separate area that leaves the full width of the input bar intact.
- It's not confusing / doesn't require a separate indicator when typing commands.
- It's more similar to the way vim operates.
- It offers a space where to put suggestions (when tab-completing commands, e.g. `:n<Tab>`).
- It also requires no additional steps to enable (as opposed to a bar item you'd add to the input bar).

(To make things clear: vi_cmd isn't going away, and the current behavior will remain the default.)

>also I don't understand why you want to add a new bar item?

If you're suggesting editing the input bar's contents directly (instead of letting the user add a bar item to it), then I'm afraid that's not going to happen. It adds a lot of needless complexity and is rather messy (both visually and logically).

>why don't you just put 3-4 if statements in the code to check if that option is set to default and only show/hide the vi_cmd if it is set to default?

Just as you want vimode to look and behave this way, others may want it to look and behave slightly differently. You want 2 states (visible when needed/always hidden), I'm offering 3 (always visible/always hidden/visible when needed). That way other people who prefer it that way can make use of it. It'll be one option.

**Comment by aranmohyeddin** [comment]
I just thought that it rarely happens that vi_cmd and the input bar both have some text in them at the same time, so we could just merge them. Because I think many people usually have IRC open in a small portion of their screen and therefore the more compact the better, but If I understood you correctly this must be what I want to be able to have:

> I just need to document it so that users who might want to hide vi_cmd completely know they can add cmd_text to another bar

So thank you very very much and thank you for your last night commits:D You are awesome:) you make my IRC life much more productive and you generally make me a happier person! Hopefully I'll be able to contribute to this wonderful plugin as soon as I get a little more familiar with git and weechat plugins:) 

Much obliged

**Comment by GermainZ** [comment]
Glad you enjoy it! :)

What you want should now be possible (as of 613ed7f755b0f10e8856ef79ecd9dac9ecbfedb9) as follows:

1. `/fset plugins.var.python.vimode.cmd_bar_behavior hidden`
2. `/fset weechat.bar.input.items`
3. Add `cmd_text` to `weechat.bar.input.items` somewhere.

The vi_cmd bar should now be permanently hidden, and the text that would usually show up in it will now show in your input bar.
